// all action types here

// to fet incidents from server
export const FETCH_INCIDENTS = 'FETCH_INCIDENTS';
export const FETCH_INCIDENTS_START = 'FETCH_INCIDENTS_START';
export const FETCH_INCIDENTS_SUCCESS = 'FETCH_INCIDENTS_SUCCESS';
export const FETCH_INCIDENTS_FAIL = 'FETCH_INCIDENTS_FAIL';

// to sort and filter incidents
export const SORT_INCIDENTS = 'SORT_INCIDENTS';
export const FILTER_INCIDENTS = 'FILTER_INCIDENTS';

// to update url
export const SORT_INCIDENTS_UPDATE_URL = 'SORT_INCIDENTS_UPDATE_URL';
export const FILTER_INCIDENTS_UPDATE_URL = 'FILTER_INCIDENTS_UPDATE_URL';

// for incident details
export const FETCH_INCIDENT_DETAIL = 'FETCH_INCIDENT_DETAIL';
export const FETCH_INCIDENT_DETAIL_START = 'FETCH_INCIDENT_DETAIL_START';
export const FETCH_INCIDENT_DETAIL_SUCCESS = 'FETCH_INCIDENT_DETAIL_SUCCESS';
export const FETCH_INCIDENT_DETAIL_FAIL = 'FETCH_INCIDENT_DETAIL_FAIL';